apiVersion: v1
kind: Service
metadata:
  name: nifi
spec:
  selector:
    app: nifi
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 32443  # Port do Minikube para acesso externo
  type: NodePort

